language: node_js

sudo: false

node_js:
  - 12

cache:
  directories:
  - node_modules

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $TRAVIS_TOKEN_KEY
  local_dir: Kvue
  on:
    branch: master
